version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-compose
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=cryptoapp
      - MYSQL_TCP_PORT=3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  mongo:
    container_name: mongo-compose
    environment:
      - MONGO_INITDB_DATABASE=cryptoapp
    ports:
      - "27017:27017"
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
  io:
    container_name: io-compose
    build:
      context: .
      dockerfile: Dockerfile.io
    ports:
      - "3001:3001"
  worker:
    container_name: worker-compose
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - NODE_ENV=compose
    depends_on:
      mysql:
        condition: service_healthy
  app:
    container_name: app-compose
    build:
      context: .
      dockerfile: ./Dockerfile.app
    environment:
      - NODE_ENV=compose
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql-data:
  mongo-data:


