version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-microservice
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=cryptoapp
      - MYSQL_TCP_PORT=3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  app:
    container_name: app-microservice
    build: .
    environment:
      - NODE_ENV=compose
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql-data:
  mongo-data:


