FROM node:18-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build
CMD node /app/dist/connect.js

FROM node:18-alpine AS final
WORKDIR /app    
COPY --from=builder ./app/dist ./dist
COPY package.json .
RUN npm install --omit=dev
CMD [ "npm", "start" ]
