version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3306
    ports:
    - 3312:3306
    expose:
      - 3306
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  app:
    depends_on:
      mysql:
        condition: service_healthy
    build: ./
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - DB_PORT=3306
    stdin_open: true
    tty: true
    